source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'RequestMgmt' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'KakaJSON', '~> 1.1.2'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'MJRefresh'
end
